### ISSUE TITLE
[Feature]: set SOC service

### ISSUE THREAD

**Issue by RomanRobotnik** [RobotnikAutomation/daly_bms#14]
### What do we want to achieve?

We want to create a new ROS service that allows calling the internal [set_soc](https://github.com/dreadnought/python-daly-bms/blob/307ed22888257aaf11722c097bcf7c51339e193e/dalybms/daly_bms.py#L394) function.

This feature is needed in order to correct internal deviations in the estimation.

### How do we plan to do it?

- Define and create new service message
- Implement the call
- The available range has to be between 0 and 100

### How can it be tested?

- Set any value and check it changes correctly in the battery data being published

**Comment by m-sanchez-rico** [comment]
Reviewed and woreking, tested in rbwatcher su-st-230620aa
